/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agents
         * @description GET /api/agents - List all agents
         */
        get: operations["list_agents"];
        put?: never;
        /**
         * Create Agent
         * @description POST /api/agents - Create a new agent
         */
        post: operations["create_agent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description GET /api/agents/:agent_id - Get agent by ID
         */
        get: operations["get_agent"];
        put?: never;
        post?: never;
        /**
         * Delete Agent
         * @description DELETE /api/agents/:agent_id - Delete agent
         */
        delete: operations["delete_agent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Sessions
         * @description GET /api/agents/:agent_id/sessions - Get agent sessions
         */
        get: operations["get_agent_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Agent
         * @description POST /api/agents/:agent_id/start - Start agent
         */
        post: operations["start_agent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Agent
         * @description POST /api/agents/:agent_id/stop - Stop agent
         */
        post: operations["stop_agent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description GET /api/artifacts/:artifact_id - Get artifact by ID
         */
        get: operations["get_artifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-bus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query Events
         * @description GET /api/event-bus
         *     Query events with cursor-based pagination
         */
        get: operations["query_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-bus/emit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emit Event
         * @description POST /api/event-bus/emit
         *     Emit a new event to the event bus
         *
         *     Used by:
         *     - Relay for emitting agent events (output_batch, permission_request, artifact, etc.)
         *     - Standalone agents that connect via HTTP
         *     - Frontend for user actions (permission responses, etc.)
         *     - External integrations
         */
        post: operations["emit_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-bus/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Cursor
         * @description GET /api/event-bus/latest
         *     Get latest cursor (for initialization)
         */
        get: operations["get_latest_cursor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-bus/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay Events
         * @description POST /api/event-bus/replay
         *     Replay historical events (for analysis)
         */
        post: operations["replay_events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description GET /api/projects - List all projects
         */
        get: operations["list_projects"];
        put?: never;
        /**
         * Create Project
         * @description POST /api/projects - Create a new project
         */
        post: operations["create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/by-name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project By Name
         * @description GET /api/projects/by-name/:name - Get project by name
         */
        get: operations["get_project_by_name"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description GET /api/projects/:project_id - Get project by ID
         */
        get: operations["get_project"];
        /**
         * Update Project
         * @description PUT /api/projects/:project_id - Update project
         */
        put: operations["update_project"];
        post?: never;
        /**
         * Delete Project
         * @description DELETE /api/projects/:project_id - Delete project
         */
        delete: operations["delete_project"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description GET /api/projects/:project_id/artifacts - List artifacts for a project
         */
        get: operations["list_artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/relays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Relays By Project
         * @description List connected relays for a specific project
         */
        get: operations["list_relays_by_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Relays
         * @description List all connected relays
         */
        get: operations["list_relays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relays/{relay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Relay
         * @description Get relay by ID
         */
        get: operations["get_relay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description GET /api/report - Get activity report
         */
        get: operations["get_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tasks
         * @description GET /api/tasks - Get today's tasks (todo, not archived)
         */
        get: operations["get_tasks"];
        put?: never;
        /**
         * Create Task
         * @description POST /api/tasks - Create a new task
         */
        post: operations["create_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backlog Tasks
         * @description GET /api/tasks/backlog - Get backlog tasks
         */
        get: operations["get_backlog_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Done Tasks
         * @description GET /api/tasks/done - Get done tasks
         */
        get: operations["get_done_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/done/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Today Done Tasks
         * @description GET /api/tasks/done/today - Get tasks marked done today
         */
        get: operations["get_today_done_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/in-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get In Progress Tasks
         * @description GET /api/tasks/in-progress - Get in-progress tasks
         */
        get: operations["get_in_progress_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Inbox Tasks
         * @description GET /api/tasks/inbox - Get inbox tasks (todo, in-progress, in-review)
         */
        get: operations["get_inbox_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task
         * @description GET /api/tasks/:task_id - Get task by ID
         */
        get: operations["get_task"];
        /**
         * Update Task
         * @description PUT /api/tasks/:task_id - Update task
         */
        put: operations["update_task"];
        post?: never;
        /**
         * Delete Task
         * @description DELETE /api/tasks/:task_id - Delete task
         */
        delete: operations["delete_task"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Task
         * @description POST /api/tasks/:task_id/archive - Archive task
         */
        post: operations["archive_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Comment
         * @description POST /api/tasks/:task_id/comments - Add comment to task
         */
        post: operations["add_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Task
         * @description POST /api/tasks/:task_id/execute - Execute task on a relay
         */
        post: operations["execute_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Task Status
         * @description POST /api/tasks/:task_id/status - Update task status
         */
        post: operations["update_task_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unarchive Task
         * @description POST /api/tasks/:task_id/unarchive - Unarchive task
         */
        post: operations["unarchive_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        args: string[];
                        command: string;
                        created_at: string;
                        /** @enum {string} */
                        execution_mode: "local" | "remote";
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        project_id: string;
                        /** @enum {string} */
                        role: "general" | "business" | "coding" | "qa";
                        /** @enum {string} */
                        status: "created" | "running" | "stopped" | "exited" | "failed";
                        updated_at: string;
                        workdir: string;
                    }[];
                };
            };
        };
    };
    create_agent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    args: string[];
                    /** @description If true, automatically start the agent after creation */
                    auto_start: boolean;
                    command: string;
                    /** @enum {string} */
                    execution_mode: "local" | "remote";
                    name: string;
                    /** Format: uuid */
                    project_id: string;
                    /** @enum {string} */
                    role: "general" | "business" | "coding" | "qa";
                    workdir: string;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agent: {
                            args: string[];
                            command: string;
                            created_at: string;
                            /** @enum {string} */
                            execution_mode: "local" | "remote";
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** Format: uuid */
                            project_id: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                            updated_at: string;
                            workdir: string;
                        };
                        /** @description Session info if auto_start was true */
                        session?: {
                            /** Format: uuid */
                            agent_id: string;
                            ended_at?: string | null;
                            /** Format: uuid */
                            id: string;
                            started_at: string;
                            /** @enum {string} */
                            status: "running" | "completed" | "failed" | "cancelled";
                        } | null;
                    };
                };
            };
        };
    };
    get_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        args: string[];
                        command: string;
                        created_at: string;
                        /** @enum {string} */
                        execution_mode: "local" | "remote";
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        project_id: string;
                        /** @enum {string} */
                        role: "general" | "business" | "coding" | "qa";
                        /** @enum {string} */
                        status: "created" | "running" | "stopped" | "exited" | "failed";
                        updated_at: string;
                        workdir: string;
                    };
                };
            };
        };
    };
    delete_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_agent_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        agent_id: string;
                        ended_at?: string | null;
                        /** Format: uuid */
                        id: string;
                        started_at: string;
                        /** @enum {string} */
                        status: "running" | "completed" | "failed" | "cancelled";
                    }[];
                };
            };
        };
    };
    start_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        agent_id: string;
                        ended_at?: string | null;
                        /** Format: uuid */
                        id: string;
                        started_at: string;
                        /** @enum {string} */
                        status: "running" | "completed" | "failed" | "cancelled";
                    };
                };
            };
        };
    };
    stop_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_artifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        agent_id?: string | null;
                        artifact_type: string;
                        created_at: string;
                        /** Format: json */
                        data: Record<string, never>;
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        project_id: string;
                        /** Format: uuid */
                        session_id?: string | null;
                        /** Format: uuid */
                        task_id: string;
                        updated_at: string;
                    };
                };
            };
        };
    };
    query_events: {
        parameters: {
            query: {
                /** @description Starting cursor (returns events with cursor > this value) */
                cursor: number;
                /** @description Event kinds to filter (comma-separated, e.g., "task.created,agent.started") */
                kinds?: string | null;
                /** @description Filter by agent ID */
                agent_id?: string | null;
                /** @description Filter by task ID */
                task_id?: string | null;
                /** @description Max events to return (default: 100, max: 1000) */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: {
                            /**
                             * Format: uuid
                             * @description Agent ID that emitted this event
                             *     Use Uuid::nil() for system events
                             */
                            agent_id: string;
                            /**
                             * @description Global monotonic sequence number (cursor)
                             *     Used for incremental consumption and replay
                             */
                            cursor: number;
                            /**
                             * Format: json
                             * @description Event-specific data (JSON)
                             */
                            data: Record<string, never>;
                            /**
                             * @description Event kind (semantic type)
                             *     Examples: "task.created", "agent.started", "artifact.github_pr_opened"
                             */
                            kind: string;
                            /**
                             * Format: uuid
                             * @description Optional session ID (for agent execution events)
                             */
                            session_id?: string | null;
                            /**
                             * Format: uuid
                             * @description Optional task ID (for task-related events)
                             */
                            task_id?: string | null;
                            /** @description Timestamp (ISO 8601) */
                            time: string;
                        }[];
                        next_cursor: number;
                    };
                };
            };
        };
    };
    emit_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Agent ID that emits this event. Defaults to System agent (nil UUID) if not provided.
                     */
                    agent_id?: string | null;
                    /** Format: json */
                    data: Record<string, never>;
                    kind: string;
                    /** Format: uuid */
                    session_id?: string | null;
                    /** Format: uuid */
                    task_id?: string | null;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    get_latest_cursor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    replay_events: {
        parameters: {
            query: {
                from_cursor: number;
                to_cursor: number;
                kinds?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Agent ID that emitted this event
                         *     Use Uuid::nil() for system events
                         */
                        agent_id: string;
                        /**
                         * @description Global monotonic sequence number (cursor)
                         *     Used for incremental consumption and replay
                         */
                        cursor: number;
                        /**
                         * Format: json
                         * @description Event-specific data (JSON)
                         */
                        data: Record<string, never>;
                        /**
                         * @description Event kind (semantic type)
                         *     Examples: "task.created", "agent.started", "artifact.github_pr_opened"
                         */
                        kind: string;
                        /**
                         * Format: uuid
                         * @description Optional session ID (for agent execution events)
                         */
                        session_id?: string | null;
                        /**
                         * Format: uuid
                         * @description Optional task ID (for task-related events)
                         */
                        task_id?: string | null;
                        /** @description Timestamp (ISO 8601) */
                        time: string;
                    }[];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query: {
                include_archived: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        business_template?: string | null;
                        coding_template?: string | null;
                        color: string;
                        created_at: string;
                        description?: string | null;
                        general_template?: string | null;
                        /** Format: uuid */
                        id: string;
                        name: string;
                        qa_template?: string | null;
                        updated_at: string;
                    }[];
                };
            };
        };
    };
    create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    color?: string | null;
                    description?: string | null;
                    name: string;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        business_template?: string | null;
                        coding_template?: string | null;
                        color: string;
                        created_at: string;
                        description?: string | null;
                        general_template?: string | null;
                        /** Format: uuid */
                        id: string;
                        name: string;
                        qa_template?: string | null;
                        updated_at: string;
                    };
                };
            };
        };
    };
    get_project_by_name: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        business_template?: string | null;
                        coding_template?: string | null;
                        color: string;
                        created_at: string;
                        description?: string | null;
                        general_template?: string | null;
                        /** Format: uuid */
                        id: string;
                        name: string;
                        qa_template?: string | null;
                        updated_at: string;
                    } | null;
                };
            };
        };
    };
    get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        business_template?: string | null;
                        coding_template?: string | null;
                        color: string;
                        created_at: string;
                        description?: string | null;
                        general_template?: string | null;
                        /** Format: uuid */
                        id: string;
                        name: string;
                        qa_template?: string | null;
                        updated_at: string;
                    };
                };
            };
        };
    };
    update_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    archived?: boolean | null;
                    business_template?: string | null;
                    coding_template?: string | null;
                    color?: string | null;
                    description?: string | null;
                    general_template?: string | null;
                    name?: string | null;
                    qa_template?: string | null;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        business_template?: string | null;
                        coding_template?: string | null;
                        color: string;
                        created_at: string;
                        description?: string | null;
                        general_template?: string | null;
                        /** Format: uuid */
                        id: string;
                        name: string;
                        qa_template?: string | null;
                        updated_at: string;
                    };
                };
            };
        };
    };
    delete_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_artifacts: {
        parameters: {
            query?: {
                type?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        agent_id?: string | null;
                        artifact_type: string;
                        created_at: string;
                        /** Format: json */
                        data: Record<string, never>;
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        project_id: string;
                        /** Format: uuid */
                        session_id?: string | null;
                        /** Format: uuid */
                        task_id: string;
                        updated_at: string;
                    }[];
                };
            };
        };
    };
    list_relays_by_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        active_session_count: number;
                        connected_at: number;
                        labels: {
                            [key: string]: string;
                        };
                        name: string;
                        projects: string[];
                        relay_id: string;
                        role: string;
                        safe_paths: string[];
                        setup_script?: string | null;
                    }[];
                };
            };
        };
    };
    list_relays: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        active_session_count: number;
                        connected_at: number;
                        labels: {
                            [key: string]: string;
                        };
                        name: string;
                        projects: string[];
                        relay_id: string;
                        role: string;
                        safe_paths: string[];
                        setup_script?: string | null;
                    }[];
                };
            };
        };
    };
    get_relay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        active_session_count: number;
                        connected_at: number;
                        labels: {
                            [key: string]: string;
                        };
                        name: string;
                        projects: string[];
                        relay_id: string;
                        role: string;
                        safe_paths: string[];
                        setup_script?: string | null;
                    };
                };
            };
        };
    };
    get_report: {
        parameters: {
            query?: {
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived_count: number;
                        comments_count: number;
                        created_count: number;
                        done_count: number;
                        /** @enum {string} */
                        period: "today" | "week" | "month";
                        state_changes_count: number;
                    };
                };
            };
        };
    };
    get_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    }[];
                };
            };
        };
    };
    create_task: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                    priority: number;
                    /** Format: uuid */
                    project_id: string;
                    /** @enum {string} */
                    status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    };
                };
            };
        };
    };
    get_backlog_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    }[];
                };
            };
        };
    };
    get_done_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    }[];
                };
            };
        };
    };
    get_today_done_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    }[];
                };
            };
        };
    };
    get_in_progress_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    }[];
                };
            };
        };
    };
    get_inbox_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    }[];
                };
            };
        };
    };
    get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    };
                };
            };
        };
    };
    update_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                    priority: number;
                    /** Format: uuid */
                    project_id: string;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    };
                };
            };
        };
    };
    delete_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    archive_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    };
                };
            };
        };
    };
    add_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        content: string;
                        create_at: string;
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        task_id: string;
                    };
                };
            };
        };
    };
    execute_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Optionally specify a relay ID to use */
                    relay_id?: string | null;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agent: {
                            args: string[];
                            command: string;
                            created_at: string;
                            /** @enum {string} */
                            execution_mode: "local" | "remote";
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** Format: uuid */
                            project_id: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                            updated_at: string;
                            workdir: string;
                        };
                        session: {
                            /** Format: uuid */
                            agent_id: string;
                            ended_at?: string | null;
                            /** Format: uuid */
                            id: string;
                            started_at: string;
                            /** @enum {string} */
                            status: "running" | "completed" | "failed" | "cancelled";
                        };
                    };
                };
            };
        };
    };
    update_task_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    };
                };
            };
        };
    };
    unarchive_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Agent executing this task, if any */
                        agent?: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "general" | "business" | "coding" | "qa";
                            /** @enum {string} */
                            status: "created" | "running" | "stopped" | "exited" | "failed";
                        } | null;
                        archived: boolean;
                        /** @description Artifacts created by the agent (e.g., GitHub PRs) */
                        artifacts: {
                            /** Format: uuid */
                            agent_id?: string | null;
                            artifact_type: string;
                            created_at: string;
                            /** Format: json */
                            data: Record<string, never>;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            project_id: string;
                            /** Format: uuid */
                            session_id?: string | null;
                            /** Format: uuid */
                            task_id: string;
                            updated_at: string;
                        }[];
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            /** @enum {string} */
                            event_type: "Create" | "StatusChange" | "Unarchived" | "Archived" | "CreateComment";
                            /** @enum {string|null} */
                            from_state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            id: string;
                            /** @enum {string|null} */
                            state?: "backlog" | "todo" | "in-progress" | "in-review" | "done" | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        project: {
                            archived: boolean;
                            business_template?: string | null;
                            coding_template?: string | null;
                            color: string;
                            created_at: string;
                            description?: string | null;
                            general_template?: string | null;
                            /** Format: uuid */
                            id: string;
                            name: string;
                            qa_template?: string | null;
                            updated_at: string;
                        };
                        /** @enum {string} */
                        status: "backlog" | "todo" | "in-progress" | "in-review" | "done";
                    };
                };
            };
        };
    };
}
