/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description GET /api/report - Get activity report
         */
        get: operations["get_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tasks
         * @description GET /api/tasks - Get today's tasks (todo, not archived)
         */
        get: operations["get_tasks"];
        put?: never;
        /**
         * Create Task
         * @description POST /api/tasks - Create a new task
         */
        post: operations["create_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backlog Tasks
         * @description GET /api/tasks/backlog - Get backlog tasks
         */
        get: operations["get_backlog_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Done Tasks
         * @description GET /api/tasks/done - Get done tasks
         */
        get: operations["get_done_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/done/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Today Done Tasks
         * @description GET /api/tasks/done/today - Get tasks marked done today
         */
        get: operations["get_today_done_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/in-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get In Progress Tasks
         * @description GET /api/tasks/in-progress - Get in-progress tasks
         */
        get: operations["get_in_progress_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Inbox Tasks
         * @description GET /api/tasks/inbox - Get inbox tasks (todo, in-progress, in-review)
         */
        get: operations["get_inbox_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task
         * @description GET /api/tasks/:task_id - Get task by ID
         */
        get: operations["get_task"];
        /**
         * Update Task
         * @description PUT /api/tasks/:task_id - Update task
         */
        put: operations["update_task"];
        post?: never;
        /**
         * Delete Task
         * @description DELETE /api/tasks/:task_id - Delete task
         */
        delete: operations["delete_task"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Task
         * @description POST /api/tasks/:task_id/archive - Archive task
         */
        post: operations["archive_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Comment
         * @description POST /api/tasks/:task_id/comments - Add comment to task
         */
        post: operations["add_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Task Status
         * @description POST /api/tasks/:task_id/status - Update task status
         */
        post: operations["update_task_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unarchive Task
         * @description POST /api/tasks/:task_id/unarchive - Unarchive task
         */
        post: operations["unarchive_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_report: {
        parameters: {
            query?: {
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived_count: number;
                        comments_count: number;
                        created_count: number;
                        done_count: number;
                        /** @enum {string} */
                        period: "Today" | "Week" | "Month";
                        state_changes_count: number;
                    };
                };
            };
        };
    };
    get_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    }[];
                };
            };
        };
    };
    create_task: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                    group: string;
                    priority: number;
                    /** @enum {string} */
                    status: "Backlog" | "Todo" | "InProgress" | "InReview" | "Done";
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    };
                };
            };
        };
    };
    get_backlog_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    }[];
                };
            };
        };
    };
    get_done_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    }[];
                };
            };
        };
    };
    get_today_done_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    }[];
                };
            };
        };
    };
    get_in_progress_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    }[];
                };
            };
        };
    };
    get_inbox_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    }[];
                };
            };
        };
    };
    get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    };
                };
            };
        };
    };
    update_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                    group: string;
                    priority: number;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    };
                };
            };
        };
    };
    delete_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    archive_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    };
                };
            };
        };
    };
    add_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        content: string;
                        create_at: string;
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        task_id: string;
                    };
                };
            };
        };
    };
    update_task_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "Backlog" | "Todo" | "InProgress" | "InReview" | "Done";
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    };
                };
            };
        };
    };
    unarchive_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        archived: boolean;
                        comments: {
                            content: string;
                            create_at: string;
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        content: string;
                        create_at: string;
                        events: {
                            datetime: string;
                            event_type: string;
                            from_state?: string | null;
                            /** Format: uuid */
                            id: string;
                            state?: string | null;
                            /** Format: uuid */
                            task_id: string;
                        }[];
                        group: string;
                        /** Format: uuid */
                        id: string;
                        priority: number;
                        status: string;
                    };
                };
            };
        };
    };
}
